### ISSUE TITLE
Tip: avoid obsolete Magit command

### ISSUE THREAD

**Issue by manuel-uberti** [thierryvolpiatto/emacs-tv-config#2]
Since `helm-ls-git` and `helm-browse-project` have become central to my workflow (another huge "thank you!"), I discovered that `magit-status-internal` has been obsoleted by `magit-status-setup-buffer` in recent Magit versions.

You probably want to do this now:
```emacs-lisp
(setq helm-ls-git-status-command #'magit-status-setup-buffer)
```

It's up to you, of course. :)

**Comment by thierryvolpiatto** [comment]
Manuel Uberti <notifications@github.com> writes:

> Since helm-ls-git and helm-browse-project have become central to my workflow (another huge "thank you!"), I discovered that magit-status-internal has been obsoleted
> by magit-status-setup-buffer in recent Emacs versions.
>
> You probably want to do this now:
>
> (setq helm-ls-git-status-command #'magit-status-setup-buffer)
>
> It's up to you, of course. :)

Thanks, but no, I use for now my own magit branch based on a old version
of magit, this to have shell completion in ":" and "!-s".

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment]
Oh cool. :)
